### ISSUE TITLE
toPrintPath isn't giving the correct original Path

### ISSUE THREAD

**Issue by paradoxe-tech** [Mathuww/LabyR#12]
```r
square <- Polygon$new(path)
print(path)

turtle$buildShapes(list(
  square
))

print(turtle$layers)
```
outputs
```text
<Path> (0, 0) -> (50, 0) -> (50, 50) -> (0, 50) -> (0, 0) 
<Path> (0, 0) -> (0, 0) -> (50, 0) -> (50, 50) -> (50, 0) -> (50, 50)
```

**Comment by poussezvousjarrive** [comment]
Created a new method set_facing(x,y) inside Path
Like this in Polygon we don't use new_path$turn but new_path$set_facing so no bug anymore but if you want more explanations écoute mon vocal Mattéo
PS : Thank God for giving me life. But maybe next time, give me wider shoulders :(
